# Setup



## Install necessary libraries & download models here

In [2]:
!pip install spacy
!python -m spacy download en_core_web_md

     ---------------------------------------- 0.0/61.0 kB ? eta -:--:--
     -------------------------- ------------- 41.0/61.0 kB 2.0 MB/s eta 0:00:01
     ---------------------------------------- 61.0/61.0 kB 1.1 MB/s eta 0:00:00
  Using cached shellingham-1.5.4-py2.py3-none-any.whl.metadata (3.5 kB)
   ---------------------------------------- 0.0/12.1 MB ? eta -:--:--
   ---------------------------------------- 0.1/12.1 MB 2.0 MB/s eta 0:00:07
   ---------------------------------------- 0.1/12.1 MB 2.0 MB/s eta 0:00:07
    --------------------------------------- 0.2/12.1 MB 1.0 MB/s eta 0:00:12
    --------------------------------------- 0.2/12.1 MB 1.1 MB/s eta 0:00:11
    --------------------------------------- 0.2/12.1 MB 1.1 MB/s eta 0:00:11
    --------------------------------------- 0.3/12.1 MB 962.4 kB/s eta 0:00:13
   - -------------------------------------- 0.3/12.1 MB 1.0 MB/s eta 0:00:12
   - -------------------------------------- 0.4/12.1 MB 1.1 MB/s eta 0:00:11
   - ---


[notice] A new release of pip is available: 24.0 -> 24.2
[notice] To update, run: python.exe -m pip install --upgrade pip


   ---------------------------------------- 6.6/6.6 MB 5.6 MB/s eta 0:00:00
   ---------------------------------------- 0.0/47.3 kB ? eta -:--:--
   ---------------------------------------- 47.3/47.3 kB 2.5 MB/s eta 0:00:00
   ---------------------------------------- 0.0/5.4 MB ? eta -:--:--
   -- ------------------------------------- 0.3/5.4 MB 10.2 MB/s eta 0:00:01
   ----- ---------------------------------- 0.7/5.4 MB 9.2 MB/s eta 0:00:01
   ------- -------------------------------- 1.0/5.4 MB 8.3 MB/s eta 0:00:01
   --------- ------------------------------ 1.3/5.4 MB 7.4 MB/s eta 0:00:01
   ----------- ---------------------------- 1.6/5.4 MB 7.2 MB/s eta 0:00:01
   -------------- ------------------------- 1.9/5.4 MB 7.1 MB/s eta 0:00:01
   ----------------- ---------------------- 2.3/5.4 MB 7.3 MB/s eta 0:00:01
   ------------------ --------------------- 2.5/5.4 MB 7.1 MB/s eta 0:00:01
   -------------------- ------------------- 2.8/5.4 MB 6.8 MB/s eta 0:00:01
   -------------------


[notice] A new release of pip is available: 24.0 -> 24.2
[notice] To update, run: python.exe -m pip install --upgrade pip


     --------------- ---------------------- 17.0/42.8 MB 606.8 kB/s eta 0:00:43
     --------------- ---------------------- 17.0/42.8 MB 606.8 kB/s eta 0:00:43
     --------------- ---------------------- 17.0/42.8 MB 607.3 kB/s eta 0:00:43
     --------------- ---------------------- 17.1/42.8 MB 607.3 kB/s eta 0:00:43
     --------------- ---------------------- 17.1/42.8 MB 607.3 kB/s eta 0:00:43
     --------------- ---------------------- 17.1/42.8 MB 607.3 kB/s eta 0:00:43
     --------------- ---------------------- 17.2/42.8 MB 607.9 kB/s eta 0:00:43
     --------------- ---------------------- 17.2/42.8 MB 606.8 kB/s eta 0:00:43
     --------------- ---------------------- 17.2/42.8 MB 607.9 kB/s eta 0:00:43
     --------------- ---------------------- 17.2/42.8 MB 606.8 kB/s eta 0:00:43
     --------------- ---------------------- 17.3/42.8 MB 607.3 kB/s eta 0:00:42
     --------------- ---------------------- 17.3/42.8 MB 607.3 kB/s eta 0:00:42
     --------------- -------------------

# Bag of Words

#### Define some training utterances

In [3]:
class Category:
  BOOKS = "BOOKS"
  CLOTHING = "CLOTHING"

train_x = ["i love the book", "this is a great book", "the fit is great", "i love the shoes"]
train_y = [Category.BOOKS, Category.BOOKS, Category.CLOTHING, Category.CLOTHING]

#### Fit vectorizer to transform text to bag-of-words vectors

In [15]:
from sklearn.feature_extraction.text import CountVectorizer

vectorizer = CountVectorizer(binary=True)
train_x_vectors = vectorizer.fit_transform(train_x)

print(vectorizer.get_feature_names_out())
print(train_x_vectors.toarray())

['book' 'fit' 'great' 'is' 'love' 'shoes' 'the' 'this']
[[1 0 0 0 1 0 1 0]
 [1 0 1 1 0 0 0 1]
 [0 1 1 1 0 0 1 0]
 [0 0 0 0 1 1 1 0]]


#### Train SVM Model

In [5]:
from sklearn import svm

clf_svm = svm.SVC(kernel='linear')
clf_svm.fit(train_x_vectors, train_y)

NameError: name 'train_x_vectors' is not defined

#### Test new utterances on trained model

In [9]:
test_x = vectorizer.transform(['i like the book'])

clf_svm.predict(test_x)

array(['BOOKS'], dtype='<U8')

In [10]:
test_x = vectorizer.transform(['shoes are alright'])

clf_svm.predict(test_x)

array(['CLOTHING'], dtype='<U8')

In [17]:
test_x = vectorizer.transform(['i like the books'])

clf_svm.predict(test_x)

array(['CLOTHING'], dtype='<U8')

In [12]:
test_x = vectorizer.transform(['i love the story'])

clf_svm.predict(test_x)

array(['CLOTHING'], dtype='<U8')

# Word Vectors

In [18]:
import spacy

nlp = spacy.load("en_core_web_md")

In [19]:
print(train_x)

['i love the book', 'this is a great book', 'the fit is great', 'i love the shoes']


In [20]:
docs = [nlp(text) for text in train_x]
train_x_word_vectors = [x.vector for x in docs]

In [21]:
print(docs[0].vector)

[-3.9804751e-01 -1.7059250e+00 -9.0664995e-01 -4.5425000e+00
 -1.1165801e+00 -2.9151249e+00  3.1752450e+00  4.0887251e+00
 -3.4474750e+00  2.3840599e+00  6.4857249e+00  2.3083498e+00
 -8.6464500e+00  2.0437698e+00  2.2699749e+00 -1.0261000e+00
  4.0915399e+00 -7.4801493e-01  1.1435002e-01 -1.9810501e+00
  1.3855026e+00  1.7070000e+00 -2.9752648e+00 -1.9328325e+00
 -1.4255500e+00 -2.0426226e+00 -3.7064652e+00 -4.3784651e-01
 -2.0860374e+00  4.4308500e+00 -1.0481000e+00 -7.8117514e-01
 -1.6870000e+00  1.9781501e+00  1.4894226e+00 -2.8325254e-01
 -1.4800999e+00  1.4303375e+00  2.6068749e+00 -1.3935680e+00
 -4.5071498e-01  1.8592875e+00  6.0194993e-01 -2.0355899e+00
  5.3853750e+00  3.3568425e+00 -2.6558499e+00 -2.5876875e+00
 -4.1877502e-01  1.1819749e+00 -1.0135007e-01 -1.6391747e+00
 -7.5115502e-01 -2.4396350e+00 -5.0018353e+00  4.4182479e-02
 -1.1361099e+00  3.4045234e+00  4.4069252e+00  1.5867125e+00
  7.3212752e+00 -6.2377250e-01 -3.5406952e+00 -1.5487249e+00
 -2.7915027e+00  4.56924

In [22]:
from sklearn import svm

clf_svm_wv = svm.SVC(kernel='linear')
clf_svm_wv.fit(train_x_word_vectors, train_y)

SVC(kernel='linear')

In [23]:
test_x = ["story is interesting", "it fits well"]
test_docs = [nlp(text) for text in test_x]
test_x_word_vectors =  [x.vector for x in test_docs]

clf_svm_wv.predict(test_x_word_vectors)

array(['BOOKS', 'CLOTHING'], dtype='<U8')

## Transformer Architecture

### Setup

In [24]:
!pip install spacy-transformers
!python -m spacy download en_core_web_trf
#!python -m spacy download en_trf_bertbaseuncased_lg

/usr/local/lib/python3.10/dist-packages/transformers/utils/generic.py:441: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  _torch_pytree._register_pytree_node(
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 457.4/457.4 MB 3.5 MB/s eta 0:00:00
✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_trf')
⚠ Restart to reload dependencies
If you are in a Jupyter or Colab notebook, you may need to restart Python in
order to load all the package's dependencies. You can do this by selecting the
'Restart kernel' or 'Restart runtime' option.


### Using Spacy to utilize BERT Model

In [4]:
!python -m spacy download en_core_web_lg

/usr/local/lib/python3.10/dist-packages/transformers/utils/generic.py:441: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  _torch_pytree._register_pytree_node(
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 587.7/587.7 MB 1.7 MB/s eta 0:00:00
✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_lg')
⚠ Restart to reload dependencies
If you are in a Jupyter or Colab notebook, you may need to restart Python in
order to load all the package's dependencies. You can do this by selecting the
'Restart kernel' or 'Restart runtime' option.


In [1]:
import spacy
import torch
from sklearn import svm

#nlp = spacy.load("en_trf_bertbaseuncased_lg")
nlp = spacy.load("en_core_web_lg")
doc = nlp("Here is some text to encode.")

/usr/local/lib/python3.10/dist-packages/transformers/utils/generic.py:441: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  _torch_pytree._register_pytree_node(
/usr/local/lib/python3.10/dist-packages/transformers/utils/generic.py:309: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  _torch_pytree._register_pytree_node(


In [2]:
class Category:
  BOOKS = "BOOKS"
  BANK = "BANK"

train_x = ["good characters and plot progression", "check out the book", "good story. would recommend", "novel recommendation", "need to make a deposit to the bank", "balance inquiry savings", "save money"]
train_y = [Category.BOOKS, Category.BOOKS, Category.BOOKS, Category.BOOKS, Category.BANK, Category.BANK, Category.BANK]

In [3]:
#from sklearn import svm

docs = [nlp(text) for text in train_x]
train_x_vectors = [doc.vector for doc in docs]
clf_svm = svm.SVC(kernel='linear')

clf_svm.fit(train_x_vectors, train_y)

test_x = ["check this story out"]
docs = [nlp(text) for text in test_x]
test_x_vectors = [doc.vector for doc in docs]

clf_svm.predict(test_x_vectors)

array(['BOOKS'], dtype='<U5')

# Stemming/Lemmatization

### Setup

In [4]:
import nltk

nltk.download('wordnet')
nltk.download('stopwords')
nltk.download('punkt')

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


True

### Stemming

In [12]:
from nltk.tokenize import word_tokenize
from nltk.stem import PorterStemmer

stemmer = PorterStemmer()

phrase = "reading the books on stories"
words = word_tokenize(phrase)

stemmed_words = []
for word in words:
  stemmed_words.append(stemmer.stem(word))

" ".join(stemmed_words)

'read the book on stori'

### Lemmatizing

In [17]:
from nltk.stem import WordNetLemmatizer

lemmatizer = WordNetLemmatizer()

phrase = "reading the books on stories"
words = word_tokenize(phrase)

lemmatized_words = []
for word in words:
  lemmatized_words.append(lemmatizer.lemmatize(word, pos='n'))

" ".join(lemmatized_words)



'reading the book on story'

# Stopwords
### Tokenize, then remove Stopwords

In [18]:
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords

stop_words = stopwords.words('english')

phrase = "Here is an example sentence demonstrating the removal of stopwords"

words = word_tokenize(phrase)

stripped_phrase = []
for word in words:
  if word not in stop_words:
    stripped_phrase.append(word)

" ".join(stripped_phrase)


'Here example sentence demonstrating removal stopwords'

# Various other techniques (spell correction, sentiment, & pos tagging)

In [19]:
!python -m textblob.download_corpora

[nltk_data] Downloading package brown to /root/nltk_data...
[nltk_data]   Unzipping corpora/brown.zip.
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Unzipping taggers/averaged_perceptron_tagger.zip.
[nltk_data] Downloading package conll2000 to /root/nltk_data...
[nltk_data]   Unzipping corpora/conll2000.zip.
[nltk_data] Downloading package movie_reviews to /root/nltk_data...
[nltk_data]   Unzipping corpora/movie_reviews.zip.
Finished.


In [20]:
from textblob import TextBlob

phrase = "the book was horrible"

tb_phrase = TextBlob(phrase)

tb_phrase.correct()

tb_phrase.tags

tb_phrase.sentiment

Sentiment(polarity=-1.0, subjectivity=1.0)

In [32]:
text = "I havv goood speling"

tb_phrase = TextBlob(text)

print(tb_phrase.correct())

t = tb_phrase.correct()

t.tags

I have good spelling


[('I', 'PRP'), ('have', 'VBP'), ('good', 'JJ'), ('spelling', 'NN')]

In [28]:
# Sentiment analysis
testimonial = TextBlob("Textblob is amazingly simple to use. What great fun!")
testimonial.sentiment

Sentiment(polarity=0.39166666666666666, subjectivity=0.4357142857142857)